[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "970eade431e2ea05963f4c7753452b1d90e79373"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "0c6935cdf488f26a24d6b7639d3652bf8e64a17ffe6cf25d1209c244b0d62761"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "a75f30473a1a049aa8a8cfee60db4f6867496fb6"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "59f12cb95d3fe6c32d8e9ccf16583823387046f479ad27761771fe2b6edc0740"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "armv7l"
git-tree-sha1 = "5369e7af4453669e8f126380e09a251bd4d763a3"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "4b95068b5f2ea15d953e3b4de006c8afeb47702fde05ca132580266e307517d7"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
git-tree-sha1 = "1f3506a9e59f61dbb586cca30843946de19b7068"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "8dc9d83f3d3aee880e9f9932124125c1229faae38054349999ac4e478cb89dda"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "af5e777b9220fbe49018e80098aaf8d5ff886901"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "743670b8259f36cff6c66d4dbf55315096d26153180fff89115c306045bcc1e9"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "35c7e756e2724377baf63788a350a7d603e3e1b8"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "148e28818ebb084ecc02b16714cfe33cef3ca6c3988981f98af174668293556b"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "33fd3d8284828f837e56f8954934b7c3b14032c7"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "baee983a04fcf9576bcc5fbbc5879a4d60f248e76f76e00ba2c7ff32d68f52f0"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.powerpc64le-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "2651029e868825bf8e791537f5bae747461777aa"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "9d0863056fdc9c16e1226d7749271f6f2049a6d2cead06dbbee3e7733bf1b146"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "975affb4b5a605dc4b423137a317fbc6fb49902d"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "b7eb8582c559afb5c89e28e2f4474ec84a63ffc937174a6e3f1499b188e8e16b"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+2/Wayland.v1.17.0.x86_64-linux-musl.tar.gz"
