[[Wayland]]
arch = "armv7l"
git-tree-sha1 = "5992744a5aac5b1de4cbf1b0103ca8669b101306"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "a347350c92f626a0250a218c8e1ad2c6ab7302858c16a228cbc2967594c55d53"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "546447dc421e1edf8c05e534f272d70c1bf04f81"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "a58f293edfa6ef9adaf54f8d08fe6b0c0f3609cbe9f17033967da2f0759f1b93"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "5962a8e4b980d0cdccf8060da9222c659b356b7f"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "432fbb20c3845381145fa08deef76eee06603f30ba5bc66c76e7e09c8c8cb699"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "armv7l"
git-tree-sha1 = "49396e4bfe24d2b26fc7f36c687db1ce2706c006"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "9f88f81fe9346c058ec767ce770c69ee1ac06ade4b06eac267060f013f47919d"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "b26d5398ad429a9bd1f2f3ae7d22e47e3f3b939c"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "1d241721b6a66afc1d09d23bbb7ebb52ce95f6fd12866c0b23b4c760c094906e"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "20ed0618f5a18af06c786ad74ba5f49b7e414d55"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "f177ac4f55ffc97c2777b3a5c23a36c8c146888dfa64ad53f410ed308276310c"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "3e71c90411b3986a6143b03f68136a76900a6fac"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "dab4af0f7a81bde864e8a0bb31fe85bea882c02b4a5c974b3555545a4da6413b"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.x86_64-linux-musl.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "bdb718a9741bfaaa176501a8b2e4f6446957994d"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "312ee5f2d4cb0b82fce16c291a28a56ba73321b40ce0ccd629d4259e6269b256"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "fcaf0ec8e3a72f4abd27250438ed3a52c892c346"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "2cdc80823500b82bed38926b05b5658f843574375567ff9264b2ff60f3cd5160"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.17.0+1/Wayland.v1.17.0.powerpc64le-linux-gnu.tar.gz"
