[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "1ab2713d8899572862d27c0ad67f810919a9fb19"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "3dd5b5e42b0f4ab1b76bfe493d3a5cebb29636acd3abefab20d3886af58eb486"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "59d20bd6d1bda5ca3d6c05b4a44fa7f1db060afe"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "4fad5bd4a19262562c756668fddbaa045c09da5a13df57320b97b3adbcb08c43"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "0d29389df0ff904606296166f69822f43c6ad730"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "17299b101854bb59bda9b1e1dcebb89eb3b07c5a4e61148e34abfd73e0d83e29"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.aarch64-unknown-freebsd.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "260a794438382f8a2af53e378bd76b7f9a2cada2"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "8c14b3ab43da92eaf7c29921584ec8a3b206ced79184e12cce3d5c26f95b6ace"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f99eb669632b0fe7ee092272aef353fdd93e1b1"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "6aab83dbcb1d6db9d5a9053991717501878192fa7feb40dd0d24c09f87227500"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "143169f00d76db8518692603490529c73b3f88b3"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "05f29e53a3bac5acaf42c1a843ed8e42a6415a0d8b9cce0901274cca5564eca2"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "67f30f774b7f55bfc538155c1a3c2950d21c7650"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "1c3f4b592a142c0a371f61198044b6ecd9340f5fbb414c2ff62679166611ce65"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "b9140cbc3cde64c9782480fdd805786fdac70252"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "079c3bd7338decfde96e753c6008dc06ce8c3727b2bb56b0f825acd512cb0fb9"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.powerpc64le-linux-gnu.tar.gz"
[[Wayland]]
arch = "riscv64"
git-tree-sha1 = "f8d2522a7404ca05acf6934def76ef67ffe650bf"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "25a4b45b12979642166c9288e660c7d463e2e71f431d8405dd95cd57482226d3"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.riscv64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "1156a1c62f59f758df3cda780d59a6c9cb3d7ae8"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "4f38f29f0079daed65e10351b1dc977a591f188d68f004b28df66c54c37f8c10"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "ba43b9caf2671e81dd6f14ab91707c4fdab03d11"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "b58cbd58582c9575be4cde07136fceb3b756b8b92c9e623dfe2be9f419b1e9a8"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.x86_64-linux-musl.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "54ff6d58470f64816972df97649d980ca2cf6b7a"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "c7629ee723035007095f13f8fcd8eb89fa051b0e843d1765976cc174f7ef7083"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+0/Wayland.v1.23.1.x86_64-unknown-freebsd.tar.gz"
