[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "267cc3409affe4ffb29bd366b13cb62923b32602"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "114ee560a9b04f814fe320d5f328dd660e0b07f7a0a1e61b76e527b2f3c16d32"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "6f24e0758511dcbdf68ec1d7284858e54ab373f1"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "4da07c6cde015865ff87dcce8b1ec3ceed455fafbf1890869bcdbc76c30232fe"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "917ce9c0c29c3b43dfc45b11e41ce36715639189"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "23fe319af70c1a9f3c8eb10dc4fae1d13a804fdcc19d652694f2afcf871d0ebc"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.aarch64-unknown-freebsd.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "28342f3f23f812314162d1d6158f231e4e4944c2"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "30ef92e1ecf8c01cb705885cdef1422ec6361c2427901d22a2323696620c919e"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.armv6l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed7dc3fb0775c2caf57f8ffe7aab86ee2749815c"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "063eb726663fec6b4662188a4ab59d7bf0eb3c53379e82afcf9fb41f230d54ae"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.armv6l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "628db34f0581467a9d75d8a39af1cd471a3e138e"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "4722881f7af30e9fede67edb664ff79b30bf32bc6b28c9a848f5aee9d95f07cf"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "21c5bb028984579006ba7fbab5ba99eb6d0c412c"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "37bc989dc893f1ba4f2975fb0ccd30dc3f728f5ed834864b3b59aba475085ff6"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "6b53673b7daee3099a981c8482f3deab466aff6a"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "60e9a15d060b03442c7c80f4cb18aa6345eae1e6353d1862e737a6aa135cbff2"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "3354dbb5832424eb738a2ca9d7b63c2688f1d1f4"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "172538b37f1d7a4897228e09dd05cca6d97aeb0c6d497941b403aa8bfb811fe7"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "9fc6134e5ab7dccdfd364fbde758e9458c0167ba"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "78e171b8d65a4b6eb0e9d5debfa09cfeb634fdef80c2ec5178c9b7003daab419"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.powerpc64le-linux-gnu.tar.gz"
[[Wayland]]
arch = "riscv64"
git-tree-sha1 = "df7fadf241bfdc9cac557c8f5b2e71b5cff3c66b"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "75c23c7e499d5c018d42e2d39d973319e712b58161ec41ce59ed6d1736fbaebc"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.riscv64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "cbe85718d7c0169671d4faa86415feb2fe31e350"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "cdf3de1af14f03d4275c7f2cf22cf8a9653507e139b28ad1dc8012b2972fe99a"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "7a1f149e30087d1f0ff8e7f89be2dfccfc69da1d"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "eeeb23070b0e14c6e277b4ee994b55b34ea648fd980877a665b6cfb245091f10"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.x86_64-linux-musl.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "1e65d7eccce387a2b9ec5ca5e2e2a53aac9c808a"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "4d0cd3d6a958f1f2f4a4945de7dd27ebda78566bff2f90f3993ed7ee4d2ace40"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+2/Wayland.v1.23.1.x86_64-unknown-freebsd.tar.gz"
