[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "270c166a705ca4d7e0d9469e1339d2eb42f9a35e"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "79e4862e14c2137e8d8d9ed1e6003643f1e05f5bb630238232fd2cc88551de0b"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "08eea1d067a4f5897cb7e7a2bf0c3d73446cef20"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "8f28edbfa589c0e25dac62dda08034e85c4cf5efb96d317af0e015c596feff2b"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "bac1263f66f96a017eb19a06914e7c01a06fc993"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "80cdfc838c8dcc2260932a008171e59501042709fcb242d8d2bf9ad57b1648ed"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.aarch64-unknown-freebsd.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c0da391ca7b6ae4b4b30c8d50c1c2f9075b416c"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "bb7556e1561cdc4468a616591ca241d1f69548c7c984e0634570124c4b945edb"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae0985ada9f4108230f6c0625be5d09c361f8f06"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "43e6f37d4a3e452e271489e2290594cc891ea538f0dece7582305c557d5ad873"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "5b1f11a3ac8bd00ba8b2d6d3f8cc0ec9b60fa5fd"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "7aca1a654db182c89efdb649ec2e5e4b95903fb0c98e446dfc287ac7f1e6036b"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "75dce38444c042c8d89823a60ccd630ccf34efe3"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "69e6ae9e0b03500cd89e35af25ce7266601d0930e2e13faf3dbd6b7111a203af"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "1b1a7920db8d94bca691aba5adad0f5689311ba4"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "1f075668c799fb0e671ba13933c22c9a2f88f36b71f0e8b131a15b3fd5198b57"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.powerpc64le-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "a7c26f0f974654c19a165fb76317f44001aa0a29"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "4c40ff439d2e84a9377d1f60a13b0d9435829bdf562faa9312b791436f40212c"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "34c1a50c2c8b7830cc5a8e358921d5805132f335"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "d9fbc8038f07b4faeb8ee2e592fb4887c2162c05d6901fc644323afd2416b164"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.x86_64-linux-musl.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "894e39773c8731ed7844129f96b734e1f5aa9349"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "710b7b40fe917d39466cded31c176f1ed573ed92cc00be1618952a0582e46a50"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.21.0+2/Wayland.v1.21.0.x86_64-unknown-freebsd.tar.gz"
