[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "ad05713eed3513818fa26f5ce3cc890b06402620"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "c48a86a9b7f17392f357e081c8230a775e2224e2cce3826a643770732cadfaef"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "e37db0941d6cdb196a937a132eb2a6bd2d88877a"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "7e5fa21b6467e01f744aa0b0775730671a25d348d988eba67e07b51b4cb40276"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "11b2f0e5c119b1d2af6a2d30bc0720d49b05748b"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "56321c0628596aba2600364e338fe8a72be4dc1e691cd42abb6d5984da361ec5"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.aarch64-unknown-freebsd.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab9198a6b286accf2bb8a23df626338f436cdeae"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "3a6c07b0ce4c488410a768ac47330be03f33ae07e3c6b185917ce7aad43f5fe5"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.armv6l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "228d468014ab6668ecf01d60b919490f68d9a5b0"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "2106de952b5d49ab8237d7a2d21c4d080b8a5ebd782067775e423107aec34ec0"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.armv6l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cca10db6324e40145314b1d659732f69346c6d80"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "a9065d18c0b3a9047e8a699a0820e2d274a1fea031e3d0b8b1d2043386ebb5a1"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63e861f4700c78cabf01423c71917c6658ab12da"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "17700e848c0624dfe2a8bdb6a61e88349d5d9e8293da1158733b7724f9611c79"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "a26814b13cfd368229022a7bd7644194d2c6a351"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "9b2e15421c7ad1160c8ee74822baa31204a0d5707df1791e27bfa9e3788577a6"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "a6324d5b12b87f1445e6ab696a747267eb548e1c"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "c20f3073dcc25923a055b388a08ee0e289a103566e395e5baec80b29b2a8b94a"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "9747eb3b0e026bc105a224e335a728333feea3ee"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "879e4ca1e814fac5d4da202e0468f8c41dd19eff1ca95fb4c26e892f30994c31"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.powerpc64le-linux-gnu.tar.gz"
[[Wayland]]
arch = "riscv64"
git-tree-sha1 = "86983bff3376cc223debbbf772b348509de9d4ad"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "b15b06c794b7dd04099b1505510ea5667d49902da8c819f6d1362c14be3c642a"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.riscv64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "909f84082eab246fea3b29cb104264c594fe467f"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "f1b8a45e82d5044dfaf24c8fca8aad674695d3a574ad02500660b7bbe327bd25"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "d4ffd6bacb065331f5e986ad919a64925e57f99d"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "445e668320398b3be15b3f5155aa63d5b3197f37456f90dc11f757615bf0a818"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.x86_64-linux-musl.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "c639dfcece4576c12d57bb4a073516036141980b"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "5454fb0c7597528a10c8914d399d6c52be2dba4753f745c81c9b5eef973350a4"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.23.1+1/Wayland.v1.23.1.x86_64-unknown-freebsd.tar.gz"
