[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "f990210f016f39e7872a4b62e64dd3d4fae69a81"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "2016f20cfb35e120e0d42f7e20bb4a81931020cc50133baa9f9b6a6ea5e6eac6"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "d952672f2924b1001f21bc09c40c2d828a196b95"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "75215457d4ac01870765420f63c92d52e34db22528ad1c683938db3f1aa487d7"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "d217d6523625c1808f190f7c09c50bdd8eaf2c97"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "28219adf833685a13dd142ba18472dd0c25e3bf20ef7b3f71161a22c6b5ff11f"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.aarch64-unknown-freebsd.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dce08d5241f70ac050e140c6fc697027fef095b8"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "5086e7a74e7e5b7e28c164d5c8148e40dfde4c4af385f4171a42e597dc8bd3de"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.armv6l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b49b092960970a9e934549b3ec24408aeb428d5e"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "9f5a29aea0f5067efe7670d139f5c876e27b4b1486348682f9845742c9878a80"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.armv6l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e4c980cf93e762d755f0b4902d8ff1e5f3d1aaa8"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "e91c297f47d34fee854e8bc9fcb63331c4db2e3880641c11d7673238e9098818"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56f6532fbfccbe72cd3837d389e223385668202e"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "16b1d4803a9d3eb98770d9bb329812bc94af389c3a7546f7c1f6d5038b2857b1"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "43084848b977d7644598b42cce0866cd9d2bc4dc"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "40bf18067491508627f35bfac2e74a57513353c884772edc1849b79ff35a5edc"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "e8e6beabf2a48d108d05aded910f91e06c62c6bb"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "b9b27387e9799b75233d3373184daffba32d77e291859d8143170d27be0c01ea"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "589f52133995e942ff3739e0168ecf7e6cd431f4"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "c0b1c58200543bd2831c0e0477a5e290baf413cd7aaac4eec149a7d520d5154c"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.powerpc64le-linux-gnu.tar.gz"
[[Wayland]]
arch = "riscv64"
git-tree-sha1 = "0217250ab82c9c2d6f20b412c32837be8d342259"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "1898a58dcae41b0c90df5811fc7c35fedeebb0ba9c6eb8ff9a2bab46a2674442"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.riscv64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "0878d3462f8e2fa4193e0e47c530a58bc490a847"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "6a184ddc197f8b53d7322aa190a5a23d2867d19d6c0a5a3ee0e9d1a7ae4cc5d6"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "53bb264c38e2331c43ace37fc519e406a3ceb5df"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "40dc0f569b7ae3ee4662f65be264e4a3b1feb8969fb85cf4aef4d8b4b92002e3"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.x86_64-linux-musl.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "744beea30c0d9196c4735effd415ccd4670a9785"
os = "freebsd"

    [[Wayland.download]]
    sha256 = "8d38f367392371db82f2b4db3e226b8feb5c872380713e2467ca31849d3e977f"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.24.0+0/Wayland.v1.24.0.x86_64-unknown-freebsd.tar.gz"
