[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "f9471203979cb28c307fcf4d264f0a384f4ca3b0"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "35e3701397657945cf3098e6251dcce2ba71a5f1fa4a2fcef93fd6160670d3b9"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.aarch64-linux-gnu.tar.gz"
[[Wayland]]
arch = "aarch64"
git-tree-sha1 = "6ddd8e9754e10f988c4d34bb0ca49ab7efbee2cb"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "58ecd24104172ae89b4fab5635146e6fcdb31fa92202ca00879ad12d55451d91"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.aarch64-linux-musl.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24002bbc08c9ed60dd884770a58f3e4f36f5bf05"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "8a268245873edf0b066a538318767923a0c7a3183ce49b8e9a0d726b3e21ddc8"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbf01097e58aa034d9d65666e6e85e1014b983e0"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "e0a7ddb4bdff8971be15e6473a870686f0fcd55fcc9227e3dc2375cca6c98638"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.armv6l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3e4dc135dd92bc71a4efe4da6e7b23af5588401c"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "e53b2693a2b794fc92b9842e7a391bcd21e10d1b237210591f8dc91c87ac72ed"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Wayland]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5617778dc537b818d574c8d2d38603e23ab1b454"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "5fb1178f9d7bb77112d7a5d0661cadb984b7897066c770f06834596fb30fabdd"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.armv7l-linux-musleabihf.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "531b06f5ec27284d1ed748c316fe9bfc10b06e4a"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "488ed2817fdc25757d9b9efce2c71e321f9b0211ee102afd6d1cb10aa96841a1"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.i686-linux-gnu.tar.gz"
[[Wayland]]
arch = "i686"
git-tree-sha1 = "0049dddaff62445df091b5baad2e4bf0bb3a105f"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "856e88267e7069be49a17235f1afe18e4fca77109f3ad35edc071533850bdb36"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.i686-linux-musl.tar.gz"
[[Wayland]]
arch = "powerpc64le"
git-tree-sha1 = "252f2237df363fb26235c76026ccf25fb5cbc4f6"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "e685726ca47a2cab391c99a38fcf63618c15a84048ddaabf789172b39893751b"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.powerpc64le-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "3c7eef5f322b19cd4b5db6b21f8cafda87b8b26c"
libc = "glibc"
os = "linux"

    [[Wayland.download]]
    sha256 = "aa89d78fa2dcd1c46055706848a152a8dab1c703b182a7f5d12290d961646f38"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.x86_64-linux-gnu.tar.gz"
[[Wayland]]
arch = "x86_64"
git-tree-sha1 = "d5fe86e1b2e920de0d9f62afddbf3e8b1e2155dd"
libc = "musl"
os = "linux"

    [[Wayland.download]]
    sha256 = "82c9a8288a0c9159412822747bdf57cdd090d63902ee9d62a86885be7557951f"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.x86_64-linux-musl.tar.gz"
